-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 19:52:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carlos-13990
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carlos-13990
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carlos-13990` DEFAULT CHARACTER SET utf8 ;
USE `carlos-13990` ;

-- -----------------------------------------------------
-- Table `carlos-13990`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlos-13990`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripion` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlos-13990`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlos-13990`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `id_genero_UNIQUE` (`id_genero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlos-13990`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlos-13990`.`departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_departamento`),
  UNIQUE INDEX `id_departamento_UNIQUE` (`id_departamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carlos-13990`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carlos-13990`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(75) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `id_categoria` INT NOT NULL,
  `id_genero` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_categoria_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_cliente_genero1_idx` (`id_genero` ASC) VISIBLE,
  INDEX `fk_cliente_departamento1_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `carlos-13990`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_genero1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `carlos-13990`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `carlos-13990`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
